Fix build with 1.81
gluon-lang/gluon pull request #968
Opened 2024-12-03 05:22 UTC by iriri

As of 1.81, `stringify` appears to always insert spaces between tokens, resulting in type names like `std :: io :: File`. Switching to `concat` avoids this issue.

Due to the use of `local_inner_macros`, we fully qualify `concat` and `stringify` in the definition of `field_decl_inner`.

2024-12-03 05:23 UTC, iriri commented
Fixes https://github.com/gluon-lang/gluon/issues/966 and https://github.com/gluon-lang/gluon/issues/967.

2024-12-04 11:29 UTC, Marwes requested changes
Thanks! CI is failing due to the lockfile being old, causing some nightly issues in dependencies, a `cargo update` should take care of it.

2024-12-06 11:24 UTC, Marwes approved these changes

2024-12-06 11:24 UTC, merged

2025-01-12 23:50 UTC, chenrui333 commented
@Marwes any plan to cut a new release? Thanks!